### ISSUE TITLE
Talk the to api

### ISSUE THREAD

**Issue by grady-lad** [giving-a-fuck-about-climate-change/carbon-inferno#1]
The current version of the app consists of test data we need setup requests to the backend and get some real data within the frontend.

What I would suggest would be to have a config files for managing the local and production endpoints.

If someone like's we could introduce some state management framework like redux , but prob over kill for now.

Looking at the [mockups](http://carbondoomsday.com/assets/mockup.png) we need the following requests to the backend:

- current ppm
- ppm over the last week
- ppm over the last year
- ppm over the last month. 

Check the [swagger api](http://api.carbondoomsday.com/#/) for what endpoints the api provides 

The responses will then need to be populated within the fe.

**Comment by titojankowski** [comment]
Excellent, it looks like this all can be accomplished with the current API using "date" for current ppm and "date__range" for weekly, yearly, monthly. For example, here's the query for "yearly" data for 2017: http://api.carbondoomsday.com/api/co2/?date__range=01%2F01%2F2017%2C12%2F31%2F2017

Are there any other endpoints you need?

**Comment by grady-lad** [comment]
@titojankowski from looking at the mockup no, everything we need is there by using date

**Comment by lwm** [comment]
Looks like this can be closed off? @grady-lad

**Comment by grady-lad** [comment]
nope @lwm we need to update the queries where there is a huge amount of data as @titojankowski suggested do 2 requests

1 -> initial req for date range (will return count)

2 -> req with limit=count
