### ISSUE TITLE
Add OpBeat to track application errors in deployment

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#10]
It's a breeze to know when the application 500s with http://opbeat.com/. I've added it for both test/prod deployments of carbondoomsday. It's free and super easy to setup! I'm sending invites for @grady-lad and @stephanieinez if you're bothered to set it up at some point.

**Comment by titojankowski** [comment]
Bump, this still worth keeping open @lwm?

**Comment by lwm** [comment]
I suppose not, at this stage, will close!
