### ISSUE TITLE
Mobile: Tiny numbers on axis

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#107]
The axis numbers are very small and misaligned. should they align with the dashed lines and be bigger?

![c7a51daa-b16c-4c27-8bdb-e81cda3010b9](https://user-images.githubusercontent.com/129060/32994344-b85a2f6a-cd1a-11e7-935a-0fb099431af1.png)

**Comment by lwm** [comment]
Ha! Doesn't look too bad, all things considered :)

**Comment by titojankowski** [comment]
Yea!!!

**Comment by grady-lad** [comment]
Haven't done any responsive work on the axis, some fiddling will need to be done to see what would be best.

**Comment by grady-lad** [comment]
@titojankowski I added some queries to resize the chart for different devices, could you check to see if the fix is suitable ?

**Comment by titojankowski** [comment]
@grady-lad 
Looks roughly the same to me, is this what you expect:
Screenshot from iPhone SE of current www.carbondoomsday.com 
![image-1](https://user-images.githubusercontent.com/129060/34459140-2b6b4ef4-ed8b-11e7-93b3-f5531cf67662.jpg)

**Comment by grady-lad** [comment]
done in #145

**Comment by titojankowski** [comment]
Looks good!

![image-1-1](https://user-images.githubusercontent.com/129060/34627118-704fe166-f203-11e7-8723-dec21b6645d9.jpg)
