### ISSUE TITLE
Date menu line

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#110]
Grey date-range menu underline should extend to the edges of the white graph box, as shown in Purin’s mockup. Screenshot from mobile but same applies in browser. (note: the dashed lines for the chart do not need to change)
![2d912380-dee4-4dc4-9814-f989bd58cf59](https://user-images.githubusercontent.com/129060/32994552-d73dd87a-cd1d-11e7-950f-9493a9a3e4bc.jpeg)

**Comment by stephanieinez** [comment]
@titojankowski Is there any way we can skip this one? This seems like it should be a small change, but actually  it would mean I need to refactor the whole App component. I'm not sure stylistically that it makes much of a difference for the amount of effort it needs to be changed.

**Comment by titojankowski** [comment]
@stephanieinez skipping!
