### ISSUE TITLE
1 week, 1 month, 1 year charts not displaying

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#115]
Skull spins infinitely...and the calculations are broken as well on all charts except "ALL" which is working great 💃 

<img width="1236" alt="screen shot 2017-12-01 at 10 38 40 am" src="https://user-images.githubusercontent.com/129060/33497766-d6f1a706-d683-11e7-96fc-b189a37891c7.png">

@grady-lad

**Comment by grady-lad** [comment]
ooops my bad, should be fixed now though!

**Comment by lwm** [comment]
Very ominous!
