### ISSUE TITLE
Amount and percent change calculation is off

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#116]
I'm taking a closer look at the "since last X" calculations.  This is important to give visitors a sense of the change from year to year, month to month. By my calculations, it rose multiple ppm last year.

However that's not what our live calculations show. For examople, today (December 1st), the 1 year chart shows +0.87 PPM (+0.21%). However, if I look at the data from our API and do the calculation manually, I get a different number.

Today: {"ppm":"406.65","date":"2017-11-30"}

1 year ago (2 options, no data for exactly 1 year ago)
ppm":"404.32","date":"2016-12-02"
"ppm":"403.84","date":"2016-11-29"

So it could be +2.33 PPM (406.65 ppm - 404.32 ppm), or +2.81 (406.65 ppm - 403.84 ppm). Either one of those are multiples bigger than +0.87 ppm which is why I point it out. Thoughts @grady-lad? How does the current calculation work?

<img width="1161" alt="screen shot 2017-12-01 at 1 21 11 pm" src="https://user-images.githubusercontent.com/129060/33503967-86079d8e-d69a-11e7-9160-5101932a658f.png">

**Comment by grady-lad** [comment]
Took a closer look here, I see what I did wrong.  I calculated the average of the year then subtracted it from the current ppm mark (make's no sense why I did this 🤦‍♂️  ).

**Comment by grady-lad** [comment]
done in #119
