### ISSUE TITLE
Update DNS to www. subdomain

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#117]
Our email accounts (including contact@carbondoomsday.com) aren't setup. To get it working we need to move to www.carbondoomsday.com instead of http://carbondoomsday.com. I think I can do most of it on namecheap or in our heroku account. I can reconfigure the CNAME parts on namecheap. Are there any changes outside of the heroku account that we need to make in the deploy process?

Heroku recommends against doing a naked domain (no www) like we're doing now, and they have a guide: https://www.namecheap.com/support/knowledgebase/article.aspx/9737/2208/pointing-a-domain-to-the-heroku-app

@lwm @grady-lad @stephanieinez

**Comment by lwm** [comment]
Damn, we need to get away from Heroku. One day! Seems like you have control of it though.

**Comment by grady-lad** [comment]
@titojankowski  I don't think any updates are required within the FE for this

**Comment by titojankowski** [comment]
I updated our DNS and the chart broke with the below error in Chrome inspector. Reverted back to the original DNS for now.

@lwm could you please update our CORS list/hosts to include "www.carbondoomsday.herokuapp.com" in the right spots?

> Failed to load https://carbondoomsday.herokuapp.com/api/co2/?ordering=-date?&limit=1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.carbondoomsday.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

similar to: https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/66

**Comment by lwm** [comment]
So, I think we can fully do this when I fix https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/88, which is an issue as a result of an upgrade. I'm working on it. I'll post here when it is done. I've updated the CORS white list.

**Comment by titojankowski** [comment]
it's updated and working!

email accounts enabled:
steph@carbondoomsday.com @stephanieinez 
luke@carbondoomsday.com @lwm 
marty@carbondoomsday.com @grady-lad 
tito@carbondoomsday.com
contact@carbondoomsday.com
accounts@carbondoomsday.com

**Comment by lwm** [comment]
Oh yes! Awesome.
