### ISSUE TITLE
Safari: Vertical graph line doesn't extend to the bottom on DAY and WEEK graph

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#118]
Looks like just a bug in Safari:
![screen shot 2017-12-01 at 6 31 59 pm](https://user-images.githubusercontent.com/129060/33510820-1c2e63c6-d6c6-11e7-8408-07737251a844.png)

Tested in Chrome on Mac, works fine.

**Comment by titojankowski** [comment]
If it's helpful, it changes with the size of the window as well

![screen shot 2017-12-01 at 6 34 25 pm](https://user-images.githubusercontent.com/129060/33510833-4b046c04-d6c6-11e7-96b8-4b30c2152ddd.png)

**Comment by grady-lad** [comment]
@titojankowski what version of safari ?

**Comment by titojankowski** [comment]
@grady-lad hmmm, don't see it happening anymore (Version 11.0.2 (13604.4.7.1.3)) -- closing for now!
