### ISSUE TITLE
Missing LICENSE file - oops

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#120]
I've AGPL'd the carbondoomsday project, I suggest the same.

https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/master/LICENSE

**Comment by lwm** [comment]
https://en.wikipedia.org/wiki/IANAL

**Comment by grady-lad** [comment]
done in #122

**Comment by lwm** [comment]
🔥 🔥 🔥
