### ISSUE TITLE
Limiting filters available (will resolve carbondoomsday/#59)

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#124]
Looking at https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/59 again and thinking about it, there doesn't seem to be any easy fix to re-style how the filters are shown on the API documentation.

Perhaps, however, we can see what carbon-inferno is already using and limit from there. Or just choose some. My guess is that I should limit to filters on only `ppm` and `date` (not `date__week/day/month` as well) and just allow `gt`, `gte`, `lt`, `lte` and  `contains`.

Any thoughts?

**Comment by grady-lad** [comment]
Carbon inferno is using the following endpoints:

1) `https://carbondoomsday-test.herokuapp.com/api/co2/?ordering=-date?&limit=1`
     This gives us the current ppm and the total amount of items the backend has
2) `https://carbondoomsday-test.herokuapp.com/api/co2/?ordering=+date&limit=15871`
     We get all the ppms the number `15781` is the total number of ppms returned from the first request
3) `https://carbondoomsday-test.herokuapp.com/api/co2/?ordering=+date&date__range=2012-12-06,2017-12-06`
Used to query between dates ranges (used for 1, week/month/year and 5 year)

I like the `gt` etc, but how would we use it for the all ? just do a `lte` todays date ?

**Comment by titojankowski** [comment]
I like the idea of limiting the endpoints shown in the UI to what carbon-
inferno currently uses. You can document the existence of the other
endpoints in the description, but they don't need to be featured in
the form UI.

On Wed, Dec 6, 2017, at 02:06 PM, grady-lad wrote:
> Carbon inferno is using the following endpoints:


>  1. https://carbondoomsday-test.herokuapp.com/api/co2/?ordering=-date?&limit=1
>     This gives us the current ppm and the total amount of items the
>     backend has
>  2. https://carbondoomsday-test.herokuapp.com/api/co2/?ordering=+date&limit=15871
>     We get all the ppms the number 15781 is the total number of ppms
>     returned from the first request
>  3. https://carbondoomsday-test.herokuapp.com/api/co2/?ordering=+date&date__range=2012-12-06,2017-12-06
>     Used to query between dates ranges (used for 1, week/month/year
>     and 5 year)> I like the gt etc, but how would we use it for the all ? just do a lte
> todays date ?> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/124#issuecomment-349790456

**Comment by lwm** [comment]
OK, thanks @grady-lad, I think I have enough to go on to not limit what you're already doing.

**Comment by lwm** [comment]
Will implement over at carbondoomsday - nice one!

**Comment by lwm** [comment]
@grady-lad @stephanieinez I'm basically cutting this down to https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/compare/lessen-filters?expand=1#diff-892e972c5d8da5babe5b627071acf70aR13 now, which allows to specify by `ppm` and uses `range` for the date - per https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/124#issuecomment-349790456. If anyone else actually uses this API ever, we can expand again 😸

**Comment by titojankowski** [comment]
@lwm looks great to me. I've used the API UI a few times since the update, this is great....make it easy to enter a search and see the results without scrolling through all the other filters. I'll let you

**Comment by lwm** [comment]
> How can we track stats on the API usage?

I thought this was already possible with https://opbeat.com/, which we currently use, but not sure. 

I'll create a ticket for this.
