### ISSUE TITLE
Create a team page

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#13]
On the current carbon-inferno.herokuapp.com, there is a 'TEAM' menu button. We have a bunch of people listed over at https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/wiki/Team. Let's try and get something together to show that.

**Comment by stephanieinez** [comment]
@lwm Feel free to assign me to this. I can try get something up this weekend.

**Comment by lwm** [comment]
Yiiipeeeeeee

**Comment by titojankowski** [comment]
@stephanieinez @lwm how about we focus 100% on the chart and hide the bottom links section for now?

Right now those links are broken and confusing, can add them in later. So propose to hide all of them:

https://www.dropbox.com/s/thx8e9ofs7pg4w0/Screenshot%202017-07-21%2012.16.42.png?dl=0

**Comment by stephanieinez** [comment]
No worries! That section will be hidden when @grady-lad deploys the changes we did today :)

**Comment by titojankowski** [comment]
@stephanieinez the TEAM content moved to https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/wiki#the-carbon-doomsday-team

There's also content there for a DATA SOURCES page, MOTIVATION, MEDIA, and USE THIS DATA

**Comment by titojankowski** [comment]
hi @stephanieinez, I'm looking at the team page on a bigger screen now, and it looks like a column in the middle opens up instead of being a grid. I would expect Purin to be on the left next to Dan. Happens on chrome and safari. Thoughts?
Screenshot: https://www.dropbox.com/s/83nvx3mwynjijm7/Screenshot%202017-09-19%2014.58.37.png?dl=0

Cheers!

**Comment by titojankowski** [comment]
It's only at a certain width -- if the window gets super wide, all the profiles go on one line.

**Comment by stephanieinez** [comment]
fixed in PR #57
