### ISSUE TITLE
Purin/Tito treasure box: Make 5 year view the default

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#130]
I think I agree. Open to discussion of course!

**Comment by titojankowski** [comment]
Woot woot!

**Comment by grady-lad** [comment]
Yeah I'm in favour of this! its pretty non trivial to switch over ill get on it

**Comment by titojankowski** [comment]
Non-trivial? I figured it was an easy switch! 🍡

**Comment by lwm** [comment]
Programming!

**Comment by grady-lad** [comment]
done in  #139
