### ISSUE TITLE
Purin/Tito treasure box: Line things up

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#131]
There isn't more on this from the email but maybe @titojankowski can call in on that one?

**Comment by titojankowski** [comment]
Two specific things I remember Purin mentioning:

1. Lining up the edge of the skull with the edge of the chart

- looking at the source, this is achieved by removing the border around skull.png

2. Lining up CARBON DOOMSDAY with 'tracking CO2...' below it

- ah, it's lined up in code, just doesn't actually LOOK lined up...how to fix?
<img width="883" alt="screen shot 2017-12-19 at 2 07 57 pm" src="https://user-images.githubusercontent.com/129060/34184853-35cf990e-e4c6-11e7-91ac-166c729d1fa8.png">

**Comment by titojankowski** [comment]
is this one for @stephanieinez?

**Comment by stephanieinez** [comment]
👍

**Comment by titojankowski** [comment]
@stephanieinez addressed this in #158, closing
