### ISSUE TITLE
Purin/Tito treasure box: Loading times - can we improve them?

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#133]
Can we do it? It would be great.

**Comment by lwm** [comment]
Hmmm, wait, the load times are amazing now - http://carbondoomsday.com/.

Is it slow for anyone?

**Comment by titojankowski** [comment]
Seems the same to me, takes 10+ seconds to load after the rest of the page is finished. Switching to 5 YEARS as default will help initial load time.

**Comment by grady-lad** [comment]
Yeah I will switch 5 years to default. And then try improve the all loading time.

**Comment by grady-lad** [comment]
In terms of improving the load times, There are a few solutions I need to investigate. But will need to define some benchmarks for what is the target we are trying to reach. I am presuming that a huge segment of our audience may be via mobile ? If this is the case we should set our benchmark to something like a shitty 3G connection on you're average mobile phone. Thoughts ?

**Comment by lwm** [comment]
Yeah, you're right. Aim low. But how in the heck do we do that then?

**Comment by grady-lad** [comment]
Deployed a fixed to production @titojankowski @lwm could you confirm if the loading times are any better ?

**Comment by grady-lad** [comment]
Loading times seem ok for me ? how about for everyone else ? 

The only thing hindering the load times are the initial requests to heroku. (This is because heroku is starting up the dyno)

**Comment by lwm** [comment]
> The only thing hindering the load times are the initial requests to heroku. (This is because heroku is starting up the dyno)

Yep, I think this is our main challenge now!!! Could close here and open over at the carbondoomsday repo.

**Comment by titojankowski** [comment]
@grady-lad wow interesting that it might just be the dyno spinning up. Would that mean that after initially loading the site (Waking up the dyno) that all page loads should be fast? Is there a tool we can use to measure the load times? @lwm

**Comment by grady-lad** [comment]
@titojankowski yeah if you load the site wait for results (the first response after the dyno wakes) and refresh the browser the site should be reasonably fast response times.

**Comment by lwm** [comment]
I think people use https://tools.pingdom.com/ but not sure. It's gotta be that dyno though!

**Comment by lwm** [comment]
I'm gonna close this off. When the dyno is down, it's like up to 3 seconds loading +. We can do network analysis after we get that sorted, if we're still not happy with the loading times. As usual, Heroku switch coming one day ...
