### ISSUE TITLE
Share current PPM via Twitter

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#134]
> Solution 2: Make it easy for them to share this chart (i.e. via twitter or embedding the graph on their site as a widget)

Yeah, we talked about that - how can we make this thing really easy to share. Would be great.

**Comment by grady-lad** [comment]
I like it ! Ill add a label help wanted for this, really need to start sharing this site out and have a few issues for people to work on if they want to help out.

**Comment by titojankowski** [comment]
Purin added this as one of the "actions" in his UI

**Comment by lwm** [comment]
Closing this in favour of https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/149!
