### ISSUE TITLE
Make frontend into a single page rather than multiple pages.

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#135]
> Solution 3: Provide ways to give a fuck and take action (i.e. like us on Github, give us some more ideas, join the team, etc.) Purin to provide new design & art direction (PDF) by Tuesday December 19

Oh, @titojankowski, did those new designs every arrive!?

**Comment by lwm** [comment]
There were some other nice notes in there too:

> - All-inclusive page (i.e. without footer or links to other pages),that includes "action" cards                                                                                                                                                            
> - Mobile view                                                                                                                                                                           
> - New art direction to reflect "giving a fuck" — currently the art direction doesn't reflect the brand

**Comment by titojankowski** [comment]
@lwm nothing new from Purin yet!

**Comment by lwm** [comment]
@titojankowski @grady-lad @stephanieinez

[carbon2.pdf](https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/files/1575257/carbon2.pdf)

**Comment by grady-lad** [comment]
The current frontend as multiple routes, these will need to be removed.

The above pdf has the desired design for the new frontend.

**Comment by lwm** [comment]
I think https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/155 is the latest version of this issue. I will close - please re-open if I got that wrong.

**Comment by titojankowski** [comment]
indeed!
