### ISSUE TITLE
Purin/Tito treasure box: Long term goals for this site (discuss)

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#136]
>Long-term goal:                                                                                                                                                                         
>- Painting the picture of what success looks like (i.e. what if CO2 level starts to come down?)                                                                                                                                                             
>-  Be the place for climate data                                                                                                                                                         
>- Playground / simulation for all sorts of scenarios                                                                                                                                    
>- Portal for actions one can take to reduce carbon emissions  

Yeah!

**Comment by titojankowski** [comment]
- "Pac Man for carbon dioxide" -- reverse climate change from your keyboard! http://ai.berkeley.edu/images/pacman_game.gif

**Comment by lwm** [comment]
I've pushed the pacman (so amazing) idea over to https://github.com/giving-a-fuck-about-climate-change/own-it/issues/10. I'll try and get the other ideas into other tickets somewhere else. Not sure anything immediately actionable for front-enders so will close off.
