### ISSUE TITLE
GET README READY FOR THOSE STARS

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#137]
https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/master/README.md

Get your shit together folks!

**Comment by lwm** [comment]
This side of the project is a mess. My repository is killing it.

**Comment by lwm** [comment]
JOKE 🚀

**Comment by grady-lad** [comment]
haha yeah Ill got on this, just introducing some test coverage, so will update the readme after that!
