### ISSUE TITLE
X-axis font distorted

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#142]
Looking good @grady-lad !

The x-axis label text is a bit squashed. Screenshot comparison of the X and Y axis with the same text: https://www.dropbox.com/s/zff17j3m51vwcb5/Screenshot%202017-12-30%2017.33.24.png?dl=0

When I deleted "viewBox="0 0 1000 40" on the container it fixes.

**Comment by grady-lad** [comment]
done in #145
