### ISSUE TITLE
Line up X-axis label with chart

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#143]
@grady-lad the label for the x-axis should be roughly centered under whatever the respective date.

Screenshot of current version, x-axis says December but the date is September.
https://www.dropbox.com/s/dmp6gcv359bfg7p/Screenshot%202017-12-30%2017.45.13.png?dl=0

See a screenshot of Coinbase/charts as a reference:
https://www.dropbox.com/s/h6wdxmksjsj3tv8/Screenshot%202017-12-30%2017.47.26.png?dl=0

**Comment by grady-lad** [comment]
done in #145

**Comment by titojankowski** [comment]
this is looking so hot!!! @grady-lad
