### ISSUE TITLE
Missing left-most x-axis label

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#144]
First x-axis label should be whatever the earliest datapoint is. ie on the ALL chart, the first x-axis label should be 'MAY 1958'. On the 5 YEAR chart, 'DEC 2012'.

Screenshot of current site: https://www.dropbox.com/s/4crex4avyao2cgv/Screenshot%202017-12-30%2017.49.45.png?dl=0

Coinbase for reference: https://www.dropbox.com/s/xx4jk4i4w51bsfz/Screenshot%202017-12-30%2017.52.32.png?dl=0

**Comment by grady-lad** [comment]
done in #145

**Comment by titojankowski** [comment]
looks great @grady-lad!
