### ISSUE TITLE
Make chart interactive + have discussed features

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#15]
Following from https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/2, we want to create the interactive chart at http://carbon-inferno.herokuapp.com/ that has buttons and safe/danger zones like in the mockup and what we've discussed in Gitter.

**Comment by titojankowski** [comment]
What are the buttons you're referring to, like the chart labels? (https://www.dropbox.com/s/qt2i47gsdo8cp3h/Screenshot%202017-07-21%2008.10.26.png?dl=0)

The safe/danger zones is post-MVP since it's not in the mockup. How about putting it in a different issue?

**Comment by lwm** [comment]
> What are the buttons you're referring to

The '1 week, month, year, all' buttons. The chart should real time change when changing. Is this already happening? I can't seem to see any data on the current front-end.

> The safe/danger zones is post-MVP since it's not in the mockup. How about putting it in a different issue?

I'll create a new issue then :+1: 

Feel free to close this one? I created to keep @grady-lad's chart work tracked.

**Comment by titojankowski** [comment]
Re: The '1 week, month, year, all' buttons. The chart should real time change when changing. Is this already happening? I can't seem to see any data on the current front-end.

The chart updates when you click the "1 MONTH" and "1 YEAR" buttons right now. BUT, you first need to click the little red shield icon in Chrome and select "allow scripts" or whatever. Try chrome, I didnt get this option when I viewed in Safari. @lwm can you see it now?

**Comment by lwm** [comment]
> @lwm can you see it now?

Following up with https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/24.

Closing this off since the buttons are doing stuff now :)
