### ISSUE TITLE
Y-axis bottom label value

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#153]
hi @grady-lad I noticed the bottom Y-axis value is the same as the top value. The bottom Y-axis value should be whatever the minimum value in the chart is. Coinbase screenshot for comparison.

<img width="369" alt="screenshot 2018-01-05 10 17 26" src="https://user-images.githubusercontent.com/129060/34626637-a6661fd8-f201-11e7-9772-005137d1a72a.png">

<img width="366" alt="screenshot 2018-01-05 10 18 16" src="https://user-images.githubusercontent.com/129060/34626665-c6694490-f201-11e7-906e-e1f7ef6278e1.png">

**Comment by grady-lad** [comment]
done
