### ISSUE TITLE
Update frontend design (last slide in PDF)

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#155]
Let's roll with the latest design, the 5th slide in the attached document, using icons from FontAwesome to start.

Here's the keynote file from Purin (with exact pixel positioning)

As well as comments:
> Great find on Font Awesome! I don't mind creating a few hand-drawn logos, but if we do end up going the Font Awesome route, let's use these for the initial set:
> 
> 1. Github: https://fontawesome.com/icons/github?style=brands
> 2. Twitter: https://fontawesome.com/icons/twitter?style=brands
> 3. Idea / Google Forms: https://fontawesome.com/icons/lightbulb?style=regular
> 4. Embed / Code: https://fontawesome.com/icons/code?style=solid
> 5. API / Gear / Cog: https://fontawesome.com/icons/cog?style=solid
> 6. Work with us / Yay!: https://fontawesome.com/icons/child?style=solid
> 
> And here's a rough idea on sizing relative to each card + titles:

[Carbon Doomsday 3.key.zip](https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/files/1647688/Carbon.Doomsday.3.key.zip)
[Carbon Doomsday 3.pdf](https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/files/1647695/Carbon.Doomsday.3.pdf)

@stephanieinez

**Comment by stephanieinez** [comment]
@titojankowski  > I can't seem to find the design file with the exact sizing/positioning, it's not the files provided?

**Comment by titojankowski** [comment]
hi @stephanieinez! It’s in the “Carbon Doomsday 3.key.zip” file attached to this issue.

.key is Keynote for Mac OS. Each of the pieces has the width/length and x,y position to help guide your design. Do you have a Mac? If not maybe we can figure something else out.

**Comment by titojankowski** [comment]
looking GREAT @stephanieinez!!!!

A few little tweaks here and there:
1. tagline: "giving a fuck about CO2 since 1958"
2. tagline: bold (currently regular)
3. .card-title font-weight: bolder (currently bold)
4. .card-container and .infocard-container width: could be more like 320 px (currently 350 px). Right now a small-ish laptop screen (1280 px wide) it only shows 2 columns and lots of blank space https://www.dropbox.com/s/0ucg7iz9wi8c1re/Screenshot%202018-02-01%2021.50.24.png?dl=0
5. .card-container height should be 100 px (currently 94 px)
6. the pinkish .card-container text color should be #D59A94
6. overall look of .card-container is tighter
	screenshot: (left is mockup, right is current in code) https://www.dropbox.com/s/cuw2z2w92pc35i1/Screenshot%202018-02-01%2020.16.33.png?dl=0
7. team-image width/height are 44 px square in the Keynote doc, which is correct in the code currently. But it doesn't match the look of the mockup - the round images should be a bit bigger than the text. I think 50 px square is a better match for the intent of the design.
8. skull and tagline positioning in #131 
	
Other:
1. border-radius is fine. In Keynote doc it says 4px, but once rendered 5 px is actually the right look. (currently 5 px in code). Or maybe there's something 
2. footer? do we still need one - wrote to ask Purin, perhaps a simple footer with date / contact us
	- Twitter: in actions
	- Contribute: in actions
	- Contact Us: ?

Looking great!!
