### ISSUE TITLE
Graph is missing significant digits

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#156]
The current graph uses round numbers (408 ppm, 407 ppm). This makes the data look a lot more jumpy. An effect of this is it makes the 1 MONTH and 1 YEAR charts less interesting and understandable as a yearly cycle, a smooth curve. Could we get back the decimals in the graph, ie 408.55 ppm? @grady-lad

**Comment by pwhisenhunt** [comment]
@titojankowski https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/pull/157 should fix this up. Mind giving it a read?
