### ISSUE TITLE
Add live test site (so we can show branch hacking live)

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#161]
Mistakenly opened on https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/issues/109. I'll set this up!

**Comment by titojankowski** [comment]
Sweet!

**Comment by titojankowski** [comment]
I checked out now.sh and surge.sh, but I don't think either one works for us.

**Comment by lwm** [comment]
We're up at https://test.carbondoomsday.com/.

I haven't really rigged up auto-deploys yet but that'll be the place where they go!

It's coming!
