### ISSUE TITLE
First time visit opinions HN #16333091 comment

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#164]
From https://news.ycombinator.com/item?id=16333091

> Nice enough design work. But as someone who works in the climate data space I think there isn't much value add here. CO2 data is already free and open and not challenging to use. It seems like a half-wasted use of electricity and contributors time to just show data and not have any call to action or resources for how to do something about the problem. From the branding and social media integration I am guessing there isn't any deep interest in actually _doing something_ about carbon emissions. It feels like the villager who is screaming about a house on fire instead of joining in the bucket line.

I suppose there is a valid POV here about the actual doing something after seeing the site. I know we just built this thing to make a graph and along the way we want to open up the scope. But I'd like to extract the sentiment in the comment and see what we can do improve.

**Comment by YPCrumble** [comment]
I'm starting to think that the biggest issue hindering progress on climate change is that climate change advocates spend so much time tearing each other down. 

The chart solves the problem that prior to this chart, climate change was not as easy to track as the price of a bitcoin. Now it is. This commenter has a very narrow view of what "doing something" entails.

If I'm trying to find an action item here, perhaps linking to @titojankowski's blog post somewhere that explains why this chart was created or highlighting the first sentence of the mission more prominently could be helpful.

**Comment by lwm** [comment]
Dead right @YPCrumble. I'm going to say that we can probably close this off here and aim to deal with these kinds of questions with a FAQ which we're tracking with https://github.com/giving-a-fuck-about-climate-change/own-it/issues/4.
