### ISSUE TITLE
Clarifying points for data sources HN #16332595 comment

### ISSUE THREAD

**Issue by decentral1se** [giving-a-fuck-about-climate-change/carbon-inferno#165]
From https://news.ycombinator.com/item?id=16333104:

> You might want to clarify that the data you're plotting are from a ground-based station on Mauna Loa. One symptom of this is that your plot does not have a title or y-axis label.
> 
> Similarly, the "global" CO2 number you display as text may be (?) an average of selected ground-based stations.
> 
> CO2 varies with altitude, and with time and spatially, of course. The ground-based stations give part of the picture, but there are also various total-column CO2 measurements, prominently from TCCON (http://tccon.ornl.gov/), and remote-sensing measurements (https://co2.jpl.nasa.gov/).
> 
> This is why clarifying what you mean by "global CO2" is important. In the light of the sophistication of what's out there, it might be good to think about where you're trying to add value.

Also from https://news.ycombinator.com/item?id=16334305

> y-axis please and some bullet points on what the data says re: long term/ mid term

**Comment by titojankowski** [comment]
https://co2.jpl.nasa.gov/ looks like a cool site -- carbon dioxide satellite data!
