### ISSUE TITLE
Flip chart X-axis so most recent date is on the right

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#17]
Most recent data should be on the right, currently opposite.

Screenshot, from left to right data should ascend from 2017-05-12 to 2017-07-06: https://www.dropbox.com/s/utosetwgqc7xyv5/Screenshot%202017-07-21%2007.30.26.png?dl=0

**Comment by grady-lad** [comment]
done  832c0bb
