### ISSUE TITLE
Heroku auto-deploy on commits to master branch

### ISSUE THREAD

**Issue by YPCrumble** [giving-a-fuck-about-climate-change/carbon-inferno#173]
I'd love to see us use Heroku's deploy hooks to automatically deploy new code each time a commit gets pushed to master branch. See https://devcenter.heroku.com/articles/github-integration

**Comment by lwm** [comment]
AFAIK, we already have this. It's mentioned over at:

> https://github.com/giving-a-fuck-about-climate-change/carbon-inferno#deploy-to-production

I believe we also have hooks to make notifications on Gitter. Perhaps it is only for testing. I do see your changes haven't made it to production. I think I may need to hand over some Heroku credentials for that.

**Comment by lwm** [comment]
From https://gitter.im/giving-a-fuck-about-climate-change/Lobby?at=5a7de6e5f283b8e5463f956d:

> I agree with those that a more "friendly" name would be good and easier for sharing :wink:

**Comment by lwm** [comment]
![deployproof](https://user-images.githubusercontent.com/1991377/36045568-65252cd0-0dd6-11e8-961f-1e1bbec7afa6.png)

**Comment by lwm** [comment]
OK, so, to summarise - there have been changes made on the master branch, merged and they've definitely been deployed but I am not seeing them live on carbondoomsday.com. @grady-lad, @stephanieinez, any ideas!?

**Comment by lwm** [comment]
OK, this is fixed!
