### ISSUE TITLE
Redirect non-SSL version of the site to SSL

### ISSUE THREAD

**Issue by YPCrumble** [giving-a-fuck-about-climate-change/carbon-inferno#175]
Currently if you enter "carbondoomsday.com" in the browser you get the non-secure version of the site.

**Comment by lwm** [comment]
Agreed, we'll need to do that. One for the NGINX + DigitalOcean Setup!

**Comment by lwm** [comment]
I've got that fixed up now! Thanks for the report @YPCrumble!

All hail Dokku.
