### ISSUE TITLE
Set graph height to 229 px and canvas to 474 px

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#18]
Currently "canvas" div (the line chart itself) displays as 525px (and doesn't fit on a laptop screen): https://www.dropbox.com/s/cv2o62my2ajfst7/Screenshot%202017-07-21%2007.57.40.png?dl=0

Purin's mockup has a graph height of 229 px.
https://www.dropbox.com/s/z1xqnuwfrd9naz3/Screenshot%202017-07-21%2007.57.08.png?dl=0

And an overall height of 474 px for the full graph (as seen in Purin's mockup, element "Rectangle 2"):
https://www.dropbox.com/s/xfco782b226xp52/Screenshot%202017-07-21%2008.05.28.png?dl=0

For reference, Coinbase line chart height is 221 px (https://www.dropbox.com/s/tbiwma8ibkv7ghv/Screenshot%202017-07-21%2007.51.34.png?dl=0).

@stephanieinez or @grady-lad ?

**Comment by grady-lad** [comment]
can we close this @titojankowski ?

**Comment by titojankowski** [comment]
Yea I’ll close it. Will take another look at the latest design.
