### ISSUE TITLE
Display zero on the CO2 PPM (y) axis

### ISSUE THREAD

**Issue by dwvisser** [giving-a-fuck-about-climate-change/carbon-inferno#187]
Don't take this the wrong way. I'm very concerned about climate change and anthropogenic CO2 emissions. Proper data display is a pet peeve of mine, though... CO2 PPM is an absolute quantity, i.e., it is an amount of something. By suppressing the zero on its axis, you erase understanding of magnitude, dumbing things down and attempting to force the audience to focus on the fact of the changes, rather than their magnitude. A 25% increase in atmospheric CO2 in the last 60 years is **huge**. Don't insult the audience's intelligence by displaying it like newspapers always display stock price changes, focused only on avoiding whitespace. I think you should put zero on the y-axis and add explanatory text that brings home why 25% increase in a critical gas concentration that should only naturally vary by about 2% is important.

**Comment by lwm** [comment]
> Don't take this the wrong way.

You've written an issue with nasty accusations. Don't assume we're insulting our users or forcing information on people. You've pushed your issue with actors in this space on us and I think that is unfair. I would say that is the **right way** to understand this issue. In the first place.

Secondly, you could have written the issue in a more constructive way (my edits in `[]`):

> [Consider] display[ing] zero on the CO2 PPM (y) axis
> A 25% increase in atmospheric CO2 in the last 60 years is huge. I think you should put zero on the y-axis and add explanatory text that brings home why 25% increase in a critical gas concentration that should only naturally vary by about 2% is important. [I think you've omitted something critical to an improved understanding on this topic. Thanks for giving a fuck. I do to.]
