### ISSUE TITLE
Set default view to 1 Month

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#19]
The default view for the app should be the '1 Month' chart:
https://www.dropbox.com/s/ilvke2yh4pvw2ys/Screenshot%202017-07-21%2008.14.27.png?dl=0

Currently nothing is selected when the app loads:
https://www.dropbox.com/s/8hfyukdomf4iopo/Screenshot%202017-07-21%2008.15.39.png?dl=0

**Comment by grady-lad** [comment]
done in 38d2712a067c63b186f7e77a1f93278f47458c20
