### ISSUE TITLE
Style frontend to mock up

### ISSUE THREAD

**Issue by grady-lad** [giving-a-fuck-about-climate-change/carbon-inferno#2]
This what we currently have [this](http://carbon-inferno.herokuapp.com/)

But what we really need is : http://carbondoomsday.com/assets/mockup.png

I would suggest leaving the graph as is now and get the mockup up and running initially

**Comment by lwm** [comment]
This can be closed off for now or? @grady-lad @stephanieinez

**Comment by stephanieinez** [comment]
@lwm yeah this can be closed I think. It's pretty much done - just need to get the chart sorted and make it more responsive.

**Comment by lwm** [comment]
> just need to get the chart sorted and make it more responsive.

Righto! I'll close this off and create two new issues for those.
