### ISSUE TITLE
Time-Choice-Header stay selected

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#20]
@stephanieinez one for you?

When chart is selected, the time-choice-header (ie 1 DAY, 1 MONTH, 1 YEAR) does not stay selected. It only selects when the mouse hovers over it:

1 MONTH selected, but time-choice-header shows nothing selected:
https://www.dropbox.com/s/fpqc5l6bjfy0sh2/Screenshot%202017-07-21%2008.17.06.png?dl=0

Should look like this instead, showing 1 MONTH selected with bold and underline: https://www.dropbox.com/s/x8ewlp3ccwl6jk3/Screenshot%202017-07-21%2008.19.15.png?dl=0

**Comment by stephanieinez** [comment]
Fixed in this PR: https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/pull/40
