### ISSUE TITLE
Remove "1 DAY" Chart

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#21]
We don't currently have intra-day data. At best it would show 1 data point which isn't much of a graph ^_^

I propose we remove it, since it can be confusing. 

thoughts? @lwm @stephanieinez @grady-lad

**Comment by titojankowski** [comment]
Here's what the mockup looks like with "1 DAY" removed:

https://www.dropbox.com/s/dj015wmo3jb4y0n/Screenshot%202017-07-21%2008.28.51.png?dl=0

**Comment by lwm** [comment]
Yep, agreed. 

I've seen that the daily data is regularly **not** updated. It took six days to get a new value one time.

**Comment by grady-lad** [comment]
done in 1ebac22f354582106caef3bba2803bcd2aa849ad
