### ISSUE TITLE
Add "Data Source" to graph

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#22]
Purin's mockup originally cites 3 data sources, "Average", "Scripps", and "NOAA" (https://www.dropbox.com/s/b841vymz354qs1c/Screenshot%202017-07-21%2008.35.19.png?dl=0)

Right now we just have one source, Mauna Loa.

I propose that we add "MAUNA LOA" to the upper left of the graph for the MVP like this: https://www.dropbox.com/s/0ucsat96443docp/Screenshot%202017-07-21%2008.34.08.png?dl=0

@stephanieinez thoughts?

**Comment by lwm** [comment]
Sounds good!

To clarify - it's actually a bit confusing, from the docstring in [views.py](https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/master/carbondoomsday/measurements/views.py#L30-L32), we see that we're actually already grabbing NOAA (the name of the organization) and Scripps (the name of the collection program) data - but it's all coming from Mauna Loa (the observatory). It seems to be fine so far to not mark the origin of measurement, I'm not sure it's important.

**Comment by stephanieinez** [comment]
Perhaps we can just include the name of the observatory somewhere on the graph, and then explain where the data is actually coming from in more detail. We could link this in our resources section?

**Comment by titojankowski** [comment]
Sounds good, so MAUNA LOA in the upper left of the graph where Purin has "Average", and a Data Sources page

**Comment by titojankowski** [comment]
Right now we have nothing in the upper left corner. should we close this and Re-open when we have another data set option?
