### ISSUE TITLE
Add safety/danger zones to chart

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#23]
Following from https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/15 and discussion there, creating this to track the addition of the danger/safety zones to the chart. /cc @stephanieinez.

**Comment by titojankowski** [comment]
Good next step is to get a mockup of this from @purincess post-MVP

**Comment by stephanieinez** [comment]
@lwm After giving this more thought, I realised that currently, due to the scale of the graph, these figures will not be displayed anyway. So maybe it's not such a good idea?

**Comment by titojankowski** [comment]
Good perspective. @lwm howabout we close this for now?

**Comment by lwm** [comment]
Aye aye!
