### ISSUE TITLE
Use Heroku domains (solves current HTTPS issue)

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#24]
The carbondoomsday.com domain doesn't have SSL certs, so that is out for now. Hopefully @titojankowski can solve that in the coming days. In the mean time, @grady-lad, use the Heroku domains: https://carbondoomsday.herokuapp.com | https://carbondoomsday-test.herokuapp.com.

Let me know if there are issues.

**Comment by titojankowski** [comment]
I'll get on the SSL stuff. I havent done it before tho, lmk if you have advice.

**Comment by grady-lad** [comment]
FIxed in d1febd09c4c25ecc8
