### ISSUE TITLE
Solve compatibility issue with Firefox

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#30]
Browsers suck.

**Comment by titojankowski** [comment]
What's the issue, is it something besides the secuirty scripts warning?

Fwiw, I cant get it the line graph display in Safari on Mac, no popups or warnings. Looks like your screenshot.

**Comment by grady-lad** [comment]
Nothing to do with security, the package I was using to get data does not seem compatible with most browsers

**Comment by titojankowski** [comment]
Good perspective! Any ideas how to resolve this?
