### ISSUE TITLE
Setup SSL and direct domain name connection

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#34]
I fell asleep the other day trying to figure this out, fell back on just a simple redirect to http://carbon-inferno.herokuapp.com

**Comment by titojankowski** [comment]
It's working! Moved our namecheap.com DNS to point at Heroku. I took asmallorange out of the loop, which was hosting our former static site). It was easy in the end, I was making it more complicated by trying to make it work with asmallorange. 

Locally I'm still getting DNS errors, but I tried it out in the Tor browser and looks like both http and https work:
http screenshot: https://www.dropbox.com/s/vkuw1kvnf9mvucb/Screenshot%202017-07-29%2020.04.16.png?dl=0

https screenshot: https://www.dropbox.com/s/zozeae27csmpyj9/Screenshot%202017-07-29%2019.59.16.png?dl=0

@lwm can you please confirm both http and https work for you? just want to get a second set of eyes on it, especially since my local DNS is still sending me to the old site

**Comment by titojankowski** [comment]
ok, confirmed it works!

**Comment by lwm** [comment]
:tada: :tada: :tada:
