### ISSUE TITLE
Use `npm run build` for Heroku deployment

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#4]
When running `npm build`, I see:

```
Note that the development build is not optimized.
To create a production build, use npm run build.
```

We should make sure that we are doing this on the Heroku deployment.

Opening to track that. Close if it's already the case.

**Comment by grady-lad** [comment]
I think we can close this @lwm ?

**Comment by lwm** [comment]
Yep, closing!
