### ISSUE TITLE
The team page on firefox has no images

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#53]
![image](https://user-images.githubusercontent.com/1991377/30780526-f119766a-a10c-11e7-936d-facff3a2070a.png)

**Comment by stephanieinez** [comment]
Whoops! Nice QAing! Damn Firefox :/ I'll as the images as files instead of grabbing their URL's.

**Comment by stephanieinez** [comment]
tested and working on Firefox 👍
