### ISSUE TITLE
Let's add Github star/watch/follow buttons

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-inferno#55]
This was mentioned ages ago by @titojankowski but I never got around to it.

I think we can embed with https://buttons.github.io/.

Should be simple. Not sure where they should go though? Front and center with graph?

**Comment by stephanieinez** [comment]
@lwm I added one to our new "contribute" page. Is this enough? Or do you want me to add one to the main page too?

**Comment by lwm** [comment]
All good then! Thanks!
