### ISSUE TITLE
Mockup has carbon dioxide readings in bigger/bolder font

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#72]
However in the current version “405 ppm” is rather skinny

I’ve asked Purin for an update on the fonts, is this helpful?

**Comment by titojankowski** [comment]
Font is “Proxima Nova Bold”

**Comment by grady-lad** [comment]
@titojankowski Looks like that font costs $$$

**Comment by stephanieinez** [comment]
fixed in #86

**Comment by titojankowski** [comment]
look gooooooood!
