### ISSUE TITLE
What should the mobile experience be?

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#74]
Smaller version of the chart? Just the current PPM? Email signup? 

I wrote Purin to get his thoughts. Add ideas here!

**Comment by grady-lad** [comment]
Graph is not responsive at the moment 😿 (this needs to be improved)
 
But I the think the mouseover event is not suitable for mobile, but not sure what a better alternative would be ?

**Comment by titojankowski** [comment]
It's better in the most recent version -- the graph is a lot bigger! Maybe no mouseover on mobile...

Purin said he'll mock it up sometime next week.

**Comment by titojankowski** [comment]
I marked it as an enhancement so we can ignore it until Purin gets back with the mockup.

**Comment by grady-lad** [comment]
related to #100

**Comment by grady-lad** [comment]
any update on this @titojankowski

**Comment by titojankowski** [comment]
I emailed Purin to follow up! I hope he joins the chat shortly.


On Mon, Dec 4, 2017, at 07:48 AM, grady-lad wrote:
> any update on this @titojankowski[1]


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/titojankowski
  2. https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/74#issuecomment-349002563

**Comment by titojankowski** [comment]
Purin and I are meeting this coming Monday at 1 PM or 1:30 PM PST for a
design review and new thoughts! That’s pretty late, 10 PM you time, but
would be great to video chat then if you’re around!

On Mon, Dec 4, 2017, at 03:44 PM, Tito Jankowski wrote:
> I emailed Purin to follow up! I hope he joins the chat shortly.
> 
> 
> On Mon, Dec 4, 2017, at 07:48 AM, grady-lad wrote:
>> any update on this @titojankowski[1]


>> — You are receiving this because you were mentioned. Reply to this
>> email directly, view it on GitHub[2], or mute the thread[3].>> 
> 


Links:

  1. https://github.com/titojankowski
  2. https://github.com/giving-a-fuck-about-climate-change/carbon-inferno/issues/74#issuecomment-349002563

**Comment by grady-lad** [comment]
@titojankowski can I  close ?

**Comment by titojankowski** [comment]
go for it! @grady-lad
