### ISSUE TITLE
Dotted Line and Dashed Line at top of chart should run the full width of the chart

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#75]
Referencing Purin’s mockup

**Comment by titojankowski** [comment]
Currently:
.App “padding: 20px;”
.time-choice-header ul padding: 0;

Instead:
.App “padding: 20px 0 20px 0;”
.time-choice-header ul “padding: 0 20px;”

**Comment by titojankowski** [comment]
Then, that creates an issue with the dotted lines. So the chart div needs a class, with pasding so the dotted lines above and below the chart have padding.

And the dotted line below the chart needs to be added. The chart div should have border-bottom and border-top. Right now div.flex-grid has border-bottom, which isn’t really the right place for the dotted line.

**Comment by grady-lad** [comment]
Currently working on this one @titojankowski

**Comment by titojankowski** [comment]
@grady-lad Now that I look closer, the mockup has the "PPM" and "DATE" labels hovering OVER the dotted lines.

Here's a screenshot: https://www.dropbox.com/s/pwijqd791gyynlg/Screenshot%202017-11-16%2010.25.36.png?dl=0

**Comment by titojankowski** [comment]
Oh let me revise that from looking at the mockup: flex-grid itself doesn't need a dotted line. But the dotted lines on the svg chart should be extended as shown in the mockup. Or something like that!

**Comment by grady-lad** [comment]
done in #87
