### ISSUE TITLE
Add “5 YEARS” chart?

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#76]
Can we see what adding a “5 YEARS” option to the top bar looks like?

**Comment by grady-lad** [comment]
Yeah this can be done, Should we reconsider 1 week and 1 month ? chart looks a bit meh under them selections

**Comment by titojankowski** [comment]
@grady-lad I think 1 WEEK and 1 MONTH are cool as reference points, illustrate the challenge that this stuff doesnt change crazily from month to month

**Comment by grady-lad** [comment]
Ok cool, 5 year soon to come so!

**Comment by grady-lad** [comment]
done in #119
