### ISSUE TITLE
Cache data?

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#77]
That way the chart doesnt have to re load every time you flip between the different views (especially with the “ALL” chart).

**Comment by grady-lad** [comment]
Caching the data will definitely come in handy for users with a poorer internet connection.

In relation to the performance of loading the 'ALL' chart there are other factors at play which I have outlined in  #90

**Comment by titojankowski** [comment]
@grady-lad should we close this one, or are you interested in investigating caching?

**Comment by grady-lad** [comment]
This will be the next thing Ill work on 😸

**Comment by titojankowski** [comment]
woot woot!

**Comment by grady-lad** [comment]
done in #119
