### ISSUE TITLE
Chart edge should align with bottom of the C of “Carbon Doomsday”

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#78]
See Purin’s mockup. Left border of the chart should be in line with the C of “Carbon Doomsday”. (in the mockup it’s “Global CO2 Levels”)

**Comment by titojankowski** [comment]
Currently in App.css, “width: 80%;”. 

This should be deleted, and add “position: relative;” instead. I think this then matches the intent of the original mockup.

**Comment by grady-lad** [comment]
@titojankowski looking on this now

**Comment by grady-lad** [comment]
done in #87
