### ISSUE TITLE
Round dot is oblong on chart

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#88]
Should be a circle, 10 px according to the Sketch mockup.

![screen shot 2017-11-16 at 2 18 20 pm](https://user-images.githubusercontent.com/129060/32919107-861db46a-cad9-11e7-8ee2-8fa17d565a32.png)

**Comment by grady-lad** [comment]
@titojankowski This may be an issue with the responsiveness of the graph. Could you confirm ?

**Comment by titojankowski** [comment]
Oh wow you're totally right. I made the window very wide and now it's oblong the other way.

Slice of the screenshot:
![screen shot 2017-11-16 at 4 03 08 pm](https://user-images.githubusercontent.com/129060/32922580-badd9036-cae7-11e7-8be9-8d9b17fb4c46.png)

Full screenshot:
![screen shot 2017-11-16 at 4 03 18 pm](https://user-images.githubusercontent.com/129060/32922584-bdd70a56-cae7-11e7-8919-a523e8e547ac.png)
