### ISSUE TITLE
SVG performance issues when rendering vast amounts of data points

### ISSUE THREAD

**Issue by grady-lad** [giving-a-fuck-about-climate-change/carbon-inferno#90]
This issue is around using an SVG for rendering the chart, SVG usually runs into performance issues when rendering huge amounts of data e.g 10000+ data points (our 'ALL' result returns roughly 10000 or so)

The 'ALL' data is now halved before rendering to help with the performance, but it still takes around 7 seconds or so to render the chart (while blocking the main UI thread !)

The alternative to SVG is to use a Canvas which will not run into the same performance issues as SVG, the problem with Canvas is that the API is more cumbersome to work with and the quality of the chart aesthetically is not as good as SVG.

I have a branch called 'coinbase-canvas' where I have played around with using a canvas but more work here needs to be done.

**Comment by titojankowski** [comment]
What about cutting down to 1/10th or 1/20th of the data points?

As well, is loading the chart asynchronously so it doesn't block the main UI an option?

**Comment by grady-lad** [comment]
#106 was merged to use 1/10th of the data points

**Comment by titojankowski** [comment]
@grady-lad Want to close this one, or is there anything left to investigate?
