### ISSUE TITLE
Is the Proxima Nova font loading correctly?

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#91]
I see Proxima Nova referenced in the CSS, but not a pointer to the font files themselves. The font looks standard right now (ie it's falling back on Helvetica or something?) @stephanieinez thoughts?

**Comment by stephanieinez** [comment]
Yep! Should be fixed in my next PR.

**Comment by stephanieinez** [comment]
Done in #104

**Comment by titojankowski** [comment]
Looks great! @stephanieinez
