### ISSUE TITLE
Chart label styling and text

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#93]
Top label (PPM):
- Radius on rectangle should be 5 pixels
- Text should be bold
- include PPM ie "405 PPM"
- Label color is #1BA69C

Bottom label (timestamp):
- Radius on rectangle should be 5 pixels
- Border thickness is 2 px
- Border color is #1BA69C
- Text should be bold
- Text color is #7A92A4

From the mockup:
![screen shot 2017-11-16 at 3 04 19 pm](https://user-images.githubusercontent.com/129060/32920766-70f30544-cadf-11e7-8e0b-9a636a478f21.png)

Currently:
![screen shot 2017-11-16 at 3 03 41 pm](https://user-images.githubusercontent.com/129060/32920752-66b86876-cadf-11e7-8170-2b390603a2a1.png)

**Comment by stephanieinez** [comment]
done in #89
