### ISSUE TITLE
Graph-filler and flex-grid border

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#94]
Currently they're both: 2px dotted #dae1e9

My interpretation of the mockup is they should be:
1px dashed #7A92A4

The mockup specifies 2px, but I think that doesn't render well, looks much bigger.

**Comment by stephanieinez** [comment]
I agree with the 1px dashed <- this looks much better. 
However, I think that it looks heaps better with the line #D0D0D5 which is the same colour as the other lines on the page. 
![screen shot 2017-11-16 at 19 11 40](https://user-images.githubusercontent.com/13995179/32922792-05b7681a-cb02-11e7-98f6-2dc527b9c67e.png)

**Comment by stephanieinez** [comment]
The #7A92A4 looks too dark

**Comment by titojankowski** [comment]
@stephanieinez I think the intention is to call out the graph a bit more with the darker lines. I'm fairly certain Purin chose it on purpose.

Also just double checked, #7A92A4 is indeed the color in the mockup.

**Comment by stephanieinez** [comment]
Kay I'll use this one then

**Comment by stephanieinez** [comment]
done in #89
