### ISSUE TITLE
Spacing on svg.linechart causes axis label to be overlapped

### ISSUE THREAD

**Issue by titojankowski** [giving-a-fuck-about-climate-change/carbon-inferno#95]
Perhaps due to the with of the column being set as 10% of the total?

![screen shot 2017-11-16 at 3 25 04 pm](https://user-images.githubusercontent.com/129060/32921430-6d02a1c6-cae2-11e7-9a2f-c5c0871bc83b.png)

Similar thing on the left hand side:
![screen shot 2017-11-16 at 3 26 26 pm](https://user-images.githubusercontent.com/129060/32921463-898a271a-cae2-11e7-826a-22df60c1fa89.png)

**Comment by grady-lad** [comment]
Cannot seem to reproduce the issue ? @titojankowski

**Comment by grady-lad** [comment]
@titojankowski maybe another responsive issue ?

**Comment by titojankowski** [comment]
@grady-lad yes sorry! it happens when I resize the window.
