### ISSUE TITLE
Better Organise CSS

### ISSUE THREAD

**Issue by grady-lad** [giving-a-fuck-about-climate-change/carbon-inferno#96]
Currently 98% of the css is managed within 'src/App.css', this makes it annoying to work in a collaborative manner. 

We can group a lot of the css styles with their corresponding components like the below folder structure: 
````javascript
/App
 |
  /button
   |
    index.js
    button.css 
````

**Comment by stephanieinez** [comment]
I'll take this one 😓

**Comment by grady-lad** [comment]
done in #146
